apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: alpine
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: alpine
    spec:
      containers:
      - image: humamilisic/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
