apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["sandbox/techtrends"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-09-09T11:09:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4ac396c7-e427-4cb8-8ba4-0435215bb288"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3111,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: steve.exe
    operation: Update
    time: "2022-09-09T11:09:50Z"
  name: techtrends
  namespace: sandbox
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: techtrends
    uid: 4ac396c7-e427-4cb8-8ba4-0435215bb288
  resourceVersion: "87768"
  uid: c4d7137f-040a-418f-b189-2b0f2a53aa87
spec:
  clusterIP: 10.43.122.103
  clusterIPs:
  - 10.43.122.103
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: techtrends
    port: 3111
    protocol: TCP
    targetPort: 3111
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-sandbox-techtrends
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
